version: "3.9"

name: "identity"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./postgres:/var/lib/postgresql/data
  identity:
    build:
      context: .
    command: start-dev
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
